include $(RTE_SDK)/mk/rte.vars.mk

# binary name
APP = NetstackTesting

# all source are stored in SRCS-y
SRCS-y := main.c

CFLAGS += -O3
CFLAGS += $(WERROR_FLAGS)

include $(RTE_SDK)/mk/rte.extapp.mk